### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by ulgoon** [Team-usai1/team-fb-31415#1]
## Description
1부터 20까지 양의 정수에 대해,
그 수가 3의 배수라면 fizz, ..  하는 기능을 구현하려 합니다.

## Tasks

- [x] fizz
- [x] buzz
- [x] fizzbuzz

## References

- [fizzbuzz](https://en.wikipedia.org/wiki/Fizz_buzz)

**Comment by kingwangzzang1234** [comment]
Good to go!!
